apiVersion: v1
kind: Service
metadata:
  name: sentinel
spec:
  selector:
    app: sentinel
  ports:
    - name: http
      protocol: TCP
      port: 80 # Service port (cluster-internal)
      targetPort: 3000 # Container port
      nodePort: 30300 # Accessible on localhost:30300 from host
  type: NodePort
